// Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, generated by their encryption device "Enigma". To find the distribution of characters, he needs to find out how many times a particular character appears in a string. But, to feed the data into his computer, "Christopher", he needs the data in lexicographic order, that is, in alphabetical order. Since, he is busy making "Christopher" better, he asks you for help. Help Alan find the frequency of characters in the encrypted strings in alphabetical order. The string contains only lower case alphabets.

// Sample Input 1 

// 4
// aman
// Sample Output 1

// a-2
// m-1
// n-1

var obj={}
var small="abcdefghijklmnopqrstuvwxyz"
for(var i=0;i<small.length;i++){
    
for(var j=0;j<N;j++)
{
   if(small[i]==string[j])
   {
       if(obj[small[i]]==undefined)
       {
           obj[small[i]]=1
       }
       else{
           obj[small[i]]=obj[small[i]]+1
       }
   }
}
}
for(var key in obj){
    console.log(key+"-"+obj[key])
}